### PR TITLE
Add docker files for server

### PR DESCRIPTION
**Pull request by Raynur2000**
Backend works, but I couldn't launch the frontend with docker and nginx. @aabounegm @enghamzasalem maybe you can give advice?

### CODE REVIEW

**Comment by Raynur2000** [comment]
@enghamzasalem, please review this PR too

**Comment by Raynur2000** [comment]
The web site works here http://zakat.coderlar.space/charity

**Review by aabounegm — COMMENTED** [review]
We already [originally had a Dockerfile](https://github.com/Zakyat/zakyat-backend/blob/d06ecfc9fd3c7793b04aff511ebea6605f151361/Dockerfile). Why was it deleted?
We also already have the docker-compose and nginx configurations [here](https://github.com/Zakyat/zakyat)

**Comment by enghamzasalem** [comment]
@aabounegm

**Comment by Raynur2000** [comment]
@aabounegm I didn't see it. But now we have Postgres DB instead of Mongo DB. And I don't understand how this https://github.com/Zakyat/zakyat repository works. There links to backend and frontend folders, but they are old.

**Comment by aabounegm** [comment]
Ok, so we simply need to modify the base image of the db container in `docker-compose` in the main repo, but mostly nothing else. That repo is the main one that connects the backend and frontend repos (as [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)) with nginx. Think of it as the glue. Currently, it points at old commits as it has not been updated in some time, but all it needs to do is just update the commit hash it refers to.

**Comment by Raynur2000** [comment]
What should I do now? I have two variants:
1) Edit and use your solution. 
If I use your solution,  I will need to change the mongo servise to postgres and edit Dockerfile in the backend. 
2) Use my solution. It works fine.

**Comment by Raynur2000** [comment]
@enghamzasalem Got it!

**Comment by Raynur2000** [comment]
I close this PR, new PR here https://github.com/Zakyat/zakyat-backend/pull/120

**Pull request closed without merging**
